server:
  port: 8087

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true

      routes:

        # =========================
        # USER SERVICE – AUTH (PUBLIC)
        # =========================
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth, /auth/**

        # =========================
        # USER SERVICE – USERS API (JWT REQUIRED)
        # =========================
        - id: user-service-users
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users, /api/users/** 
          filters:
            - RewritePath=/api/users(?<remaining>/?.*), /users${remaining}

        # =========================
        # USER SERVICE – USER PROFILE (JWT REQUIRED)
        # =========================
        - id: user-service-user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user, /api/user/** 
          filters:
            - RewritePath=/api/user(?<remaining>/?.*), /users${remaining}

        # =========================
        # USER SERVICE – DASHBOARD (JWT REQUIRED)
        # =========================
        - id: user-service-dashboard
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/dashboard, /api/dashboard/** 
          filters:
            - RewritePath=/api/dashboard(?<remaining>/?.*), /dashboard${remaining}

        # =========================
        # TRAVEL SERVICE
        # =========================
        - id: travel-service
          uri: lb://TRAVEL-SERVICE
          predicates:
            - Path=/api/travels/**

        # =========================
        # MEDIA SERVICE (JWT REQUIRED)
        # =========================
        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/media, /api/media/** 
          filters:
            - RewritePath=/api/media(?<remaining>/?.*), /media${remaining}

jwt:
  secret: KfTpBkd4/IZ8utP7ia3aZ8z7AM92lQmYJvgqxOGNR5o=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/